---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "39"
year: "2021"
contributor: 
- Christian Winkler
title: "Digitalisierung am Deutschen Museum – alles andere als retro"
abstract: "Die Digitalisierung und Onlinepräsentation von Buchbeständen ist in der Welt der Bibliotheken schon lange kein Novum mehr. Der Artikel beschreibt am Beispiel der Projekte der Bibliothek des Deutschen Museums die verschiedenen Formen von Bestandsdigitalisierung in chronologischer Reihenfolge. Dabei wird nicht nur die Genese eines konkreten Digitalisierungskonzeptes verständlich, sondern auch generell Kriterien bibliothekarischer Digitalisierung und ihrer Vorzüge nachvollziehbar."
abstractalt: "The digitization and online presentation of book collections has long since ceased to be a novelty in the world of libraries. Using the projects of the library of the Deutsches Museum as an example, the article describes the various forms of collection digitization in chronological order. In doing so, not only the genesis of a concrete digitization concept becomes clear, but also general criteria of library digitization and its advantages."
pdf: "https://doi.org/10.18452/23450"
doi: "10.18452/23450"
date: 2021-09-30
comments: false
sharing: true
footer: true

---
