---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "39"
year: "2021"
contributor: 
- Dominic Göhring
title: "Begegnung der anderen Art: Roboter in deutschen Bibliotheken"
pdf: "https://doi.org/10.18452/23447"
doi: "10.18452/23447"
abstract: "Der Beitrag begibt sich auf Spurensuche und versucht einen Überblick zu geben, in welcher Funktion Roboter in deutschen Bibliotheken eingesetzt werden, wie Roboter von Nutzenden und Belegschaft angenommen werden und was die Grenzen des Einsatzes der Bibliotheksrobotik sind. Dazu wurden vier Einrichtungen in einem schriftlichen beziehungsweise telefonischen Interview zu den sich im Einsatz befindlichen Robotern befragt und die Ergebnisse in dieser Umfrage dargestellt."
date: 2021-09-28
comments: false
sharing: true
footer: true

---
