---
citation:
  type: article-journal
  container-title: "LIBREAS. Library Ideas"
  volume: 39
  volume-title: Roboter und Automatisierung
license: "CC BY"
lang: "de"
doi: "10.18452/23448"
date: "2021-09-30"
date-format: "MMMM YYYY"
author:
title: "Feminismus, Algorithmen, Gender-Data-Gap und was das alles mit Bibliotheks- und Informationswissenschaft zu tun hat"

format:
  html:
    other-links:
      - text: PDF
        href: main.pdf
        icon: file-pdf
      - text: EDOC HU Berlin
        href: https://doi.org/10.18452/23448
        icon: file-pdf
    shift-heading-level-by: -1

---
