---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "39"
year: "2021"
contributor: 
- Sara Juen
title: "Feminismus, Algorithmen, Gender-Data-Gap und was das alles mit Bibliotheks- und Informationswissenschaft zu tun hat"
abstract: "In den letzten Jahren gab es vermehrt Berichte 체ber unethisches Handeln in Technologiekonzernen und Hinweise darauf, dass Algorithmen nicht neutral handeln, sondern gesellschaftlich bestehende Ungerechtigkeiten weiterf체hren oder diese sogar versch채rfen. Der vorliegende Artikel gibt einen Einblick in diese Thematik und zeigt auf, warum dieses Thema f체r die Bibliotheks- und Informationswissenschaft relevant ist."
abstractalt: "In recent years, there have been increasing reports about unethical actions in technology corporations and indications that algorithms do not act neutrally, but rather continue existing social injustices or even intensify them. This article provides insight into this issue and shows why this topic is relevant to library and information science."
pdf: "https://doi.org/10.18452/23448"
doi: "10.18452/23448"
date: 2021-09-30
comments: false
sharing: true
footer: true

---
