---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "39"
year: "2021"
contributor: 
- "Redaktion LIBREAS"
title: "Das liest die LIBREAS, Nummer #8 (Frühling / Sommer 2021)"
pdf: "https://doi.org/10.18452/23452"
doi: "10.18452/23452"
date: 2021-09-30
comments: false
sharing: true
footer: true

---
