---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "39"
year: "2021"
contributor: 
- Victoria Geske
- Yannick Paulsen
- Heidrun Wiesenmüller
- Daniel Brenn
- Beat Mattmann
title: "Communitybuilding über Discord – der DACH-Bibliothekswesen-Server"
abstract: "Discord ist ein Dienst, der ursprünglich aus der Gaming-Szene kommt, mit dem man als Gruppe online miteinander kommunizieren kann. Selbst erstellte Server können gestaltet werden, wie es zum jeweiligen Freundeskreis oder der Community passt, und umfassen sowohl schriftlichen als auch audiovisuellen Austausch. Den hier thematisierten Server für Bibliotheksmenschen gibt es seit Februar 2021. Das Interview fand am 22.06.21 über Videochat statt. Zu diesem Zeitpunkt waren knapp 1200 Nutzer*innen registriert."
pdf: "https://doi.org/10.18452/23451"
doi: "10.18452/23451"
date: 2021-10-03
comments: false
sharing: true
footer: true

---
