---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "39"
year: "2021"
contributor: 
- Andreas Urech
- Marisa Eberle
- Roger Burkhard
title: "Entwicklung von nützlichen Einsatzszenarien für Soziale Roboter in den Bibliotheken der FHNW"
pdf: "https://doi.org/10.18452/23445"
doi: "10.18452/23445"
abstract: "Soziale Roboter sind fähig, mit Menschen zu kommunizieren oder zu interagieren und erfreuen sich zunehmender Beliebtheit in Berufs- und Alltagssituationen. Deshalb ist in der FHNW Campus Brugg-Windisch Bibliothek in Zusammenarbeit mit dem FHNW Robo-Lab seit Dezember 2019 ein Roboter des Modells Pepper im Einsatz. Der Roboter beantwortet häufige Fragen, erklärt die Registrierung für die Bibliotheksbenutzung, gibt Tipps zu Verpflegungsmöglichkeiten und bittet die Anwesenden kurz vor der abendlichen Schliessung, die Bibliothek zu verlassen. In einem partizipativen Prozess wird der Roboter durch Studierende laufend weiterentwickelt und die bestehenden Szenarien werden mit der Hochschule für Angewandte Psychologie evaluiert. In diesem Artikel werden die Erkenntnisse aus einer Evaluation nach dem Human Centered Design Prozess vorgestellt, in welcher Szenarien anhand von Usability Tests mit Bibliotheksbenutzenden untersucht wurden."
abstractalt: "Social robots are able to communicate or interact with humans. They are becoming increasingly popular in professional and everyday situations. For this reason, a robot has been in use at the FHNW Campus Brugg-Windisch library in collaboration with the FHNW Robo-Lab since December 2019. The robot answers frequently asked questions, explains how to register to use the library, gives hints on catering options and asks the students to leave the library shortly before closing time in the evening. In a participatory process, the robot is continuously developed by students and the existing scenarios are evaluated with the School of Applied Psychology. This article presents the findings from an evaluation based on the human-centered design process, in which scenarios were examined using usability tests with library users."
date: 2021-09-15
comments: false
sharing: true
footer: true

---
