---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "39"
year: "2021"
contributor: 
- Redaktion LIBREAS
title: "Editorial #39: Roboter und Automatisierung"
pdf: "https://doi.org/10.18452/23437"
doi: "10.18452/23437"
date: 2021-09-30
comments: false
sharing: true
footer: true

---