---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "39"
year: "2021"
contributor: 
- Karsten Schuldt
title: "Wie von der Automatisierung in Bibliotheken erzählen?"
pdf: "https://doi.org/10.18452/23449"
doi: "10.18452/23449"
abstract: "Ein Buch zur Einführung und Verbreitung von Computern in Bibliotheken im Kanton Genf wird als Anlass genommen zu diskutieren, wie eine Geschichte von Technik in Bibliotheken erzählt werden und was aus ihr gelernt werden kann. Einer der Autoren des Buches hat im Laufe seiner Karriere weitere Werke vorgelegt, welche die Entwicklung von Computern praxisorientiert begleiteten. Dies bietet eine gute Möglichkeit, die Veränderungen seines Blickwinkels zu beschreiben. Dabei geht es im Text aber nicht um eine Kritik dieser Werke, sondern darum zu diskutieren, wie eine Geschichtsschreibung aufgebaut sein kann, welche möglichst viele Fragen stellt, von denen die heutige Praxis profiieren könnte."
date: 2021-09-28
comments: false
sharing: true
footer: true

---
