name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Provide Fonts
        run: |
          mkdir -p /usr/share/fonts/Atkinson_Hyperlegible
          cp -r fonts/ /usr/share/fonts/Atkinson_Hyperlegible/
          fc-cache -fv

      - name: Install TeX Live
        run: |
          sudo apt-get install -y texlive
          sudo tlmgr init-usertree
          sudo tlmgr install texlive-lang-german babel
          
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure TinyTeX is in PATH
        run: |
          echo "$HOME/.TinyTeX/bin/$(uname -s | tr '[:upper:]' '[:lower:]')" >> $GITHUB_PATH

      - name: Render and Publish
        if: github.event_name == 'push'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}