name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CICD:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Provide Fonts
        run: |
          mkdir /usr/share/fonts/Atkinson_Hyperlegible
          cp -r fonts/ /usr/share/fonts/Atkinson_Hyperlegible/
          fc-cache -fv
      
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
          
      - name: Render and Publish 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}